### ISSUE TITLE
Add "Donate" Page/Link

### ISSUE THREAD

**Issue by JT003** [ARCC-RACE/arcc-website#6]
A wish list of AMZN/WMT/HD gift cards, list of materials, list of mentoring/assistance should help the organization fund through some smaller expenses. Be clear that ARCC is not a 501C non-profit org and the donations will not be tax-deductable.

**Comment by caelinsutch** [comment]
Should we wait unti we register as a 501C? What service do you think we should use?

**Comment by caelinsutch** [comment]
Looking at [this](https://donorbox.org/)

**Comment by caelinsutch** [comment]
Maybe a how can you help page

**Comment by JT003** [comment]
Donate page will work. Then design the page to take different kinds of
donations your organization needs to grow.
How did you find out about Donor box? Compare for (low) costs, features
(you need), and balance convenience and security.

Be aware of some possible downsides and prepare countermeasures. For
example, credit-card thieves would donate a small amount to test the credit
cards but will incur transaction fees that non-profit organizations are
stuck with - "donations" where the transaction fees are more than the
amount donated.

**Comment by JT003** [comment]
Look into  https://www.donorschoose.org/ as well. Maybe the donate page can
have multiple methods of donation to cater to different types of donors.

**Comment by JT003** [comment]
Actually, donorchoose.org is NOT a good choice if ARCC/R.A.C.E. is to stand
alone for donation solicitation. Anything related to JHS will need to be
approved at the highest level, especially donation solicitation.

**Comment by caelinsutch** [comment]
Support page finished, still need to figure out the actual backend process.Paypal might be best option.

**Comment by caelinsutch** [comment]
Going to table this for now...
